# Generated by Django 4.0.1 on 2022-01-28 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=120)),
                ('Body', models.TextField()),
                ('IsPublished', models.BooleanField(default=True)),
                ('CreateDate', models.DateTimeField(default=datetime.datetime(2022, 1, 29, 1, 41, 4, 104256))),
                ('PublishDate', models.DateTimeField(default=datetime.datetime(2022, 1, 29, 1, 41, 4, 104256), null=True)),
                ('BlogImage', models.ImageField(upload_to='Images/Posts/%Y/%m/%d/')),
                ('Author', models.ForeignKey(on_delete=models.SET('DELETED'), to='post.author')),
                ('PostCategory', models.ForeignKey(default='1', on_delete=models.SET('DELETED'), to='post.category')),
                ('Tags', models.ManyToManyField(to='post.Tag')),
            ],
        ),
    ]
