# Generated by Django 4.0.1 on 2022-01-28 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 1, 43, 28, 786725)),
        ),
        migrations.AlterField(
            model_name='post',
            name='PublishDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 1, 43, 28, 786725), null=True),
        ),
    ]
