# Generated by Django 4.0.1 on 2022-01-28 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_createdate_alter_post_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 1, 53, 37, 170719)),
        ),
        migrations.AlterField(
            model_name='post',
            name='PublishDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 1, 53, 37, 170719), null=True),
        ),
    ]
